// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/agent.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest contains hardware, kernel, and daemon metadata from the compute node.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CertificateCn string                 `protobuf:"bytes,2,opt,name=certificate_cn,json=certificateCn,proto3" json:"certificate_cn,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsName        string                 `protobuf:"bytes,4,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	KernelVersion string                 `protobuf:"bytes,5,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	DockerVersion string                 `protobuf:"bytes,6,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"`
	CpuCoresTotal int32                  `protobuf:"varint,7,opt,name=cpu_cores_total,json=cpuCoresTotal,proto3" json:"cpu_cores_total,omitempty"`
	MemoryMbTotal int64                  `protobuf:"varint,8,opt,name=memory_mb_total,json=memoryMbTotal,proto3" json:"memory_mb_total,omitempty"`
	DiskGbTotal   int64                  `protobuf:"varint,9,opt,name=disk_gb_total,json=diskGbTotal,proto3" json:"disk_gb_total,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimestampUnix int64                  `protobuf:"varint,11,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetCertificateCn() string {
	if x != nil {
		return x.CertificateCn
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *RegisterRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *RegisterRequest) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *RegisterRequest) GetCpuCoresTotal() int32 {
	if x != nil {
		return x.CpuCoresTotal
	}
	return 0
}

func (x *RegisterRequest) GetMemoryMbTotal() int64 {
	if x != nil {
		return x.MemoryMbTotal
	}
	return 0
}

func (x *RegisterRequest) GetDiskGbTotal() int64 {
	if x != nil {
		return x.DiskGbTotal
	}
	return 0
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

// RegisterResponse returns the authoritative IDs and operating parameters from the Control Plane.
type RegisterResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AgentId              string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeId               string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Registered           bool                   `protobuf:"varint,3,opt,name=registered,proto3" json:"registered,omitempty"`
	HeartbeatIntervalSec int32                  `protobuf:"varint,4,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	ReconcileIntervalSec int32                  `protobuf:"varint,5,opt,name=reconcile_interval_sec,json=reconcileIntervalSec,proto3" json:"reconcile_interval_sec,omitempty"`
	Capabilities         []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Message              string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

func (x *RegisterResponse) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *RegisterResponse) GetReconcileIntervalSec() int32 {
	if x != nil {
		return x.ReconcileIntervalSec
	}
	return 0
}

func (x *RegisterResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// OperationEnvelope represents an authoritative typed operation dispatched by the Control Plane.
type OperationEnvelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	OperationType  string                 `protobuf:"bytes,2,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	ResourceId     string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvironmentId  string                 `protobuf:"bytes,5,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	PayloadJson    string                 `protobuf:"bytes,6,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	CreatedAtUnix  int64                  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Cancel         bool                   `protobuf:"varint,9,opt,name=cancel,proto3" json:"cancel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperationEnvelope) Reset() {
	*x = OperationEnvelope{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationEnvelope) ProtoMessage() {}

func (x *OperationEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationEnvelope.ProtoReflect.Descriptor instead.
func (*OperationEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *OperationEnvelope) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationEnvelope) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *OperationEnvelope) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *OperationEnvelope) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *OperationEnvelope) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *OperationEnvelope) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *OperationEnvelope) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *OperationEnvelope) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *OperationEnvelope) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

// OperationResponse reports the execution progress, result, and telemetry back to Control Plane.
type OperationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperationId     string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // PENDING, RUNNING, SUCCEEDED, FAILED, CANCELLED
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ResultJson      string                 `protobuf:"bytes,5,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	CompletedAtUnix int64                  `protobuf:"varint,6,opt,name=completed_at_unix,json=completedAtUnix,proto3" json:"completed_at_unix,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,7,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *OperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *OperationResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *OperationResponse) GetCompletedAtUnix() int64 {
	if x != nil {
		return x.CompletedAtUnix
	}
	return 0
}

func (x *OperationResponse) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

// HeartbeatRequest delivers node status and capacity metrics.
type HeartbeatRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeId             string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsagePercent    float64                `protobuf:"fixed64,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent float64                `protobuf:"fixed64,4,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	DiskUsagePercent   float64                `protobuf:"fixed64,5,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	ContainerCount     int32                  `protobuf:"varint,6,opt,name=container_count,json=containerCount,proto3" json:"container_count,omitempty"`
	HealthStatus       string                 `protobuf:"bytes,7,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"` // HEALTHY, DEGRADED, UNHEALTHY
	SentAtUnix         int64                  `protobuf:"varint,8,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *HeartbeatRequest) GetDiskUsagePercent() float64 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *HeartbeatRequest) GetContainerCount() int32 {
	if x != nil {
		return x.ContainerCount
	}
	return 0
}

func (x *HeartbeatRequest) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *HeartbeatRequest) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

// HeartbeatResponse acknowledges receipt and provides directives (e.g. rotation trigger or drain).
type HeartbeatResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged          bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	TriggerReconciliation bool                   `protobuf:"varint,2,opt,name=trigger_reconciliation,json=triggerReconciliation,proto3" json:"trigger_reconciliation,omitempty"`
	RotateCertificate     bool                   `protobuf:"varint,3,opt,name=rotate_certificate,json=rotateCertificate,proto3" json:"rotate_certificate,omitempty"`
	DrainNode             bool                   `protobuf:"varint,4,opt,name=drain_node,json=drainNode,proto3" json:"drain_node,omitempty"`
	ServerTimeUnix        int64                  `protobuf:"varint,5,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetTriggerReconciliation() bool {
	if x != nil {
		return x.TriggerReconciliation
	}
	return false
}

func (x *HeartbeatResponse) GetRotateCertificate() bool {
	if x != nil {
		return x.RotateCertificate
	}
	return false
}

func (x *HeartbeatResponse) GetDrainNode() bool {
	if x != nil {
		return x.DrainNode
	}
	return false
}

func (x *HeartbeatResponse) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

// InventoryRequest describes local container and resource allocations.
type InventoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InventoryJson  string                 `protobuf:"bytes,3,opt,name=inventory_json,json=inventoryJson,proto3" json:"inventory_json,omitempty"`
	ReportedAtUnix int64                  `protobuf:"varint,4,opt,name=reported_at_unix,json=reportedAtUnix,proto3" json:"reported_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InventoryRequest) Reset() {
	*x = InventoryRequest{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryRequest) ProtoMessage() {}

func (x *InventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryRequest.ProtoReflect.Descriptor instead.
func (*InventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *InventoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InventoryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InventoryRequest) GetInventoryJson() string {
	if x != nil {
		return x.InventoryJson
	}
	return ""
}

func (x *InventoryRequest) GetReportedAtUnix() int64 {
	if x != nil {
		return x.ReportedAtUnix
	}
	return 0
}

type InventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *InventoryResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// StateRequest communicates current active containers and statuses.
type StateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActualStateJson string                 `protobuf:"bytes,3,opt,name=actual_state_json,json=actualStateJson,proto3" json:"actual_state_json,omitempty"`
	ReportedAtUnix  int64                  `protobuf:"varint,4,opt,name=reported_at_unix,json=reportedAtUnix,proto3" json:"reported_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StateRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StateRequest) GetActualStateJson() string {
	if x != nil {
		return x.ActualStateJson
	}
	return ""
}

func (x *StateRequest) GetReportedAtUnix() int64 {
	if x != nil {
		return x.ReportedAtUnix
	}
	return 0
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	DriftDetected bool                   `protobuf:"varint,2,opt,name=drift_detected,json=driftDetected,proto3" json:"drift_detected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StateResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *StateResponse) GetDriftDetected() bool {
	if x != nil {
		return x.DriftDetected
	}
	return false
}

// EventRequest transmits lifecycle and alert events.
type EventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Severity       string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // INFO, WARN, ERROR, CRITICAL
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,6,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *EventRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *EventRequest) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recorded      bool                   `protobuf:"varint,1,opt,name=recorded,proto3" json:"recorded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *EventResponse) GetRecorded() bool {
	if x != nil {
		return x.Recorded
	}
	return false
}

// MetricsRequest batches time-series telemetry.
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MetricsJson   string                 `protobuf:"bytes,3,opt,name=metrics_json,json=metricsJson,proto3" json:"metrics_json,omitempty"`
	SampledAtUnix int64                  `protobuf:"varint,4,opt,name=sampled_at_unix,json=sampledAtUnix,proto3" json:"sampled_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *MetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetricsRequest) GetMetricsJson() string {
	if x != nil {
		return x.MetricsJson
	}
	return ""
}

func (x *MetricsRequest) GetSampledAtUnix() int64 {
	if x != nil {
		return x.SampledAtUnix
	}
	return 0
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recorded      bool                   `protobuf:"varint,1,opt,name=recorded,proto3" json:"recorded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsResponse) GetRecorded() bool {
	if x != nil {
		return x.Recorded
	}
	return false
}

// ReconcileRequest provides desired state and queries differences.
type ReconcileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActualStateJson string                 `protobuf:"bytes,3,opt,name=actual_state_json,json=actualStateJson,proto3" json:"actual_state_json,omitempty"`
	TimestampUnix   int64                  `protobuf:"varint,4,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReconcileRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReconcileRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReconcileRequest) GetActualStateJson() string {
	if x != nil {
		return x.ActualStateJson
	}
	return ""
}

func (x *ReconcileRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type ReconcileResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DesiredStateJson   string                 `protobuf:"bytes,1,opt,name=desired_state_json,json=desiredStateJson,proto3" json:"desired_state_json,omitempty"`
	HasDrift           bool                   `protobuf:"varint,2,opt,name=has_drift,json=hasDrift,proto3" json:"has_drift,omitempty"`
	RepairInstructions []string               `protobuf:"bytes,3,rep,name=repair_instructions,json=repairInstructions,proto3" json:"repair_instructions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ReconcileResponse) GetDesiredStateJson() string {
	if x != nil {
		return x.DesiredStateJson
	}
	return ""
}

func (x *ReconcileResponse) GetHasDrift() bool {
	if x != nil {
		return x.HasDrift
	}
	return false
}

func (x *ReconcileResponse) GetRepairInstructions() []string {
	if x != nil {
		return x.RepairInstructions
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x13primecloud.agent.v1\"\x80\x04\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12%\n" +
	"\x0ecertificate_cn\x18\x02 \x01(\tR\rcertificateCn\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_name\x18\x04 \x01(\tR\x06osName\x12%\n" +
	"\x0ekernel_version\x18\x05 \x01(\tR\rkernelVersion\x12%\n" +
	"\x0edocker_version\x18\x06 \x01(\tR\rdockerVersion\x12&\n" +
	"\x0fcpu_cores_total\x18\a \x01(\x05R\rcpuCoresTotal\x12&\n" +
	"\x0fmemory_mb_total\x18\b \x01(\x03R\rmemoryMbTotal\x12\"\n" +
	"\rdisk_gb_total\x18\t \x01(\x03R\vdiskGbTotal\x12H\n" +
	"\x06labels\x18\n" +
	" \x03(\v20.primecloud.agent.v1.RegisterRequest.LabelsEntryR\x06labels\x12%\n" +
	"\x0etimestamp_unix\x18\v \x01(\x03R\rtimestampUnix\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x02\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"registered\x18\x03 \x01(\bR\n" +
	"registered\x124\n" +
	"\x16heartbeat_interval_sec\x18\x04 \x01(\x05R\x14heartbeatIntervalSec\x124\n" +
	"\x16reconcile_interval_sec\x18\x05 \x01(\x05R\x14reconcileIntervalSec\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\xd0\x02\n" +
	"\x11OperationEnvelope\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0eoperation_type\x18\x02 \x01(\tR\roperationType\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12%\n" +
	"\x0eenvironment_id\x18\x05 \x01(\tR\renvironmentId\x12!\n" +
	"\fpayload_json\x18\x06 \x01(\tR\vpayloadJson\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x12\x16\n" +
	"\x06cancel\x18\t \x01(\bR\x06cancel\"\xff\x01\n" +
	"\x11OperationResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12\x1f\n" +
	"\vresult_json\x18\x05 \x01(\tR\n" +
	"resultJson\x12*\n" +
	"\x11completed_at_unix\x18\x06 \x01(\x03R\x0fcompletedAtUnix\x12)\n" +
	"\x10progress_percent\x18\a \x01(\x05R\x0fprogressPercent\"\xc2\x02\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x04 \x01(\x01R\x12memoryUsagePercent\x12,\n" +
	"\x12disk_usage_percent\x18\x05 \x01(\x01R\x10diskUsagePercent\x12'\n" +
	"\x0fcontainer_count\x18\x06 \x01(\x05R\x0econtainerCount\x12#\n" +
	"\rhealth_status\x18\a \x01(\tR\fhealthStatus\x12 \n" +
	"\fsent_at_unix\x18\b \x01(\x03R\n" +
	"sentAtUnix\"\xe6\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x125\n" +
	"\x16trigger_reconciliation\x18\x02 \x01(\bR\x15triggerReconciliation\x12-\n" +
	"\x12rotate_certificate\x18\x03 \x01(\bR\x11rotateCertificate\x12\x1d\n" +
	"\n" +
	"drain_node\x18\x04 \x01(\bR\tdrainNode\x12(\n" +
	"\x10server_time_unix\x18\x05 \x01(\x03R\x0eserverTimeUnix\"\x97\x01\n" +
	"\x10InventoryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12%\n" +
	"\x0einventory_json\x18\x03 \x01(\tR\rinventoryJson\x12(\n" +
	"\x10reported_at_unix\x18\x04 \x01(\x03R\x0ereportedAtUnix\"7\n" +
	"\x11InventoryResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\x98\x01\n" +
	"\fStateRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12*\n" +
	"\x11actual_state_json\x18\x03 \x01(\tR\x0factualStateJson\x12(\n" +
	"\x10reported_at_unix\x18\x04 \x01(\x03R\x0ereportedAtUnix\"Z\n" +
	"\rStateResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12%\n" +
	"\x0edrift_detected\x18\x02 \x01(\bR\rdriftDetected\"\xcd\x01\n" +
	"\fEventRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\x12(\n" +
	"\x10occurred_at_unix\x18\x06 \x01(\x03R\x0eoccurredAtUnix\"+\n" +
	"\rEventResponse\x12\x1a\n" +
	"\brecorded\x18\x01 \x01(\bR\brecorded\"\x8f\x01\n" +
	"\x0eMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\fmetrics_json\x18\x03 \x01(\tR\vmetricsJson\x12&\n" +
	"\x0fsampled_at_unix\x18\x04 \x01(\x03R\rsampledAtUnix\"-\n" +
	"\x0fMetricsResponse\x12\x1a\n" +
	"\brecorded\x18\x01 \x01(\bR\brecorded\"\x99\x01\n" +
	"\x10ReconcileRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12*\n" +
	"\x11actual_state_json\x18\x03 \x01(\tR\x0factualStateJson\x12%\n" +
	"\x0etimestamp_unix\x18\x04 \x01(\x03R\rtimestampUnix\"\x8f\x01\n" +
	"\x11ReconcileResponse\x12,\n" +
	"\x12desired_state_json\x18\x01 \x01(\tR\x10desiredStateJson\x12\x1b\n" +
	"\thas_drift\x18\x02 \x01(\bR\bhasDrift\x12/\n" +
	"\x13repair_instructions\x18\x03 \x03(\tR\x12repairInstructions2\xf5\x05\n" +
	"\fAgentService\x12W\n" +
	"\bRegister\x12$.primecloud.agent.v1.RegisterRequest\x1a%.primecloud.agent.v1.RegisterResponse\x12f\n" +
	"\x10StreamOperations\x12&.primecloud.agent.v1.OperationResponse\x1a&.primecloud.agent.v1.OperationEnvelope(\x010\x01\x12^\n" +
	"\rSendHeartbeat\x12%.primecloud.agent.v1.HeartbeatRequest\x1a&.primecloud.agent.v1.HeartbeatResponse\x12`\n" +
	"\x0fReportInventory\x12%.primecloud.agent.v1.InventoryRequest\x1a&.primecloud.agent.v1.InventoryResponse\x12T\n" +
	"\vReportState\x12!.primecloud.agent.v1.StateRequest\x1a\".primecloud.agent.v1.StateResponse\x12T\n" +
	"\vReportEvent\x12!.primecloud.agent.v1.EventRequest\x1a\".primecloud.agent.v1.EventResponse\x12Z\n" +
	"\rReportMetrics\x12#.primecloud.agent.v1.MetricsRequest\x1a$.primecloud.agent.v1.MetricsResponse\x12Z\n" +
	"\tReconcile\x12%.primecloud.agent.v1.ReconcileRequest\x1a&.primecloud.agent.v1.ReconcileResponseB:Z8github.com/primecloud/primecloud-agent/internal/protocolb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: primecloud.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 1: primecloud.agent.v1.RegisterResponse
	(*OperationEnvelope)(nil), // 2: primecloud.agent.v1.OperationEnvelope
	(*OperationResponse)(nil), // 3: primecloud.agent.v1.OperationResponse
	(*HeartbeatRequest)(nil),  // 4: primecloud.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 5: primecloud.agent.v1.HeartbeatResponse
	(*InventoryRequest)(nil),  // 6: primecloud.agent.v1.InventoryRequest
	(*InventoryResponse)(nil), // 7: primecloud.agent.v1.InventoryResponse
	(*StateRequest)(nil),      // 8: primecloud.agent.v1.StateRequest
	(*StateResponse)(nil),     // 9: primecloud.agent.v1.StateResponse
	(*EventRequest)(nil),      // 10: primecloud.agent.v1.EventRequest
	(*EventResponse)(nil),     // 11: primecloud.agent.v1.EventResponse
	(*MetricsRequest)(nil),    // 12: primecloud.agent.v1.MetricsRequest
	(*MetricsResponse)(nil),   // 13: primecloud.agent.v1.MetricsResponse
	(*ReconcileRequest)(nil),  // 14: primecloud.agent.v1.ReconcileRequest
	(*ReconcileResponse)(nil), // 15: primecloud.agent.v1.ReconcileResponse
	nil,                       // 16: primecloud.agent.v1.RegisterRequest.LabelsEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	16, // 0: primecloud.agent.v1.RegisterRequest.labels:type_name -> primecloud.agent.v1.RegisterRequest.LabelsEntry
	0,  // 1: primecloud.agent.v1.AgentService.Register:input_type -> primecloud.agent.v1.RegisterRequest
	3,  // 2: primecloud.agent.v1.AgentService.StreamOperations:input_type -> primecloud.agent.v1.OperationResponse
	4,  // 3: primecloud.agent.v1.AgentService.SendHeartbeat:input_type -> primecloud.agent.v1.HeartbeatRequest
	6,  // 4: primecloud.agent.v1.AgentService.ReportInventory:input_type -> primecloud.agent.v1.InventoryRequest
	8,  // 5: primecloud.agent.v1.AgentService.ReportState:input_type -> primecloud.agent.v1.StateRequest
	10, // 6: primecloud.agent.v1.AgentService.ReportEvent:input_type -> primecloud.agent.v1.EventRequest
	12, // 7: primecloud.agent.v1.AgentService.ReportMetrics:input_type -> primecloud.agent.v1.MetricsRequest
	14, // 8: primecloud.agent.v1.AgentService.Reconcile:input_type -> primecloud.agent.v1.ReconcileRequest
	1,  // 9: primecloud.agent.v1.AgentService.Register:output_type -> primecloud.agent.v1.RegisterResponse
	2,  // 10: primecloud.agent.v1.AgentService.StreamOperations:output_type -> primecloud.agent.v1.OperationEnvelope
	5,  // 11: primecloud.agent.v1.AgentService.SendHeartbeat:output_type -> primecloud.agent.v1.HeartbeatResponse
	7,  // 12: primecloud.agent.v1.AgentService.ReportInventory:output_type -> primecloud.agent.v1.InventoryResponse
	9,  // 13: primecloud.agent.v1.AgentService.ReportState:output_type -> primecloud.agent.v1.StateResponse
	11, // 14: primecloud.agent.v1.AgentService.ReportEvent:output_type -> primecloud.agent.v1.EventResponse
	13, // 15: primecloud.agent.v1.AgentService.ReportMetrics:output_type -> primecloud.agent.v1.MetricsResponse
	15, // 16: primecloud.agent.v1.AgentService.Reconcile:output_type -> primecloud.agent.v1.ReconcileResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
